// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZFTC_EMS.Data;

#nullable disable

namespace NZFTC_EMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126052951_Seed_MoreDemoData")]
    partial class Seed_MoreDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTodo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("calendarevents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "NZFTC EMS officially launched!",
                            End = new DateTime(2025, 11, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 3,
                            IsPublicHoliday = false,
                            IsTodo = false,
                            OwnerUsername = "System",
                            Start = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "System Go-Live"
                        },
                        new
                        {
                            Id = 2,
                            Description = "15-minute catch-up for IT team.",
                            End = new DateTime(2025, 11, 21, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            EventType = 1,
                            IsPublicHoliday = false,
                            IsTodo = false,
                            OwnerUsername = "sarah@nzftc.local",
                            Start = new DateTime(2025, 11, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily Stand-up – IT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Approve timesheets before 3 PM.",
                            End = new DateTime(2025, 11, 19, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 3,
                            IsPublicHoliday = false,
                            IsTodo = true,
                            OwnerUsername = "admin@nzftc.local",
                            Start = new DateTime(2025, 11, 19, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Payroll Cut-off"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sick leave",
                            End = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 4,
                            IsPublicHoliday = false,
                            IsTodo = false,
                            OwnerUsername = "sarah@nzftc.local",
                            Start = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Approved leave – Sarah Williams"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Annual leave",
                            End = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 4,
                            IsPublicHoliday = false,
                            IsTodo = false,
                            OwnerUsername = "daniel@nzftc.local",
                            Start = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Approved leave – Daniel Lee"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<byte>("PayFrequency")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("PayGradeId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("JobPositionId");

                    b.HasIndex("PayGradeId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1001,
                            Address = "N/A",
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Email = "admin@nzftc.local",
                            EmployeeCode = "NZFTC1001",
                            FirstName = "Temp",
                            Gender = "Other",
                            JobPositionId = 11,
                            LastName = "Admin",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 8,
                            StartDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1002,
                            Address = "123 Finance Street",
                            Birthday = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Email = "emp@nzftc.local",
                            EmployeeCode = "NZFTC1002",
                            FirstName = "TEMP",
                            Gender = "Male",
                            JobPositionId = 4,
                            LastName = "Emp",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 7,
                            StartDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1003,
                            Address = "42 Eden Terrace",
                            Birthday = new DateTime(1997, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "sarah@nzftc.local",
                            EmployeeCode = "NZFTC1003",
                            FirstName = "Sarah",
                            Gender = "Female",
                            JobPositionId = 22,
                            LastName = "Williams",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 6,
                            StartDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1004,
                            Address = "19 Queen Street",
                            Birthday = new DateTime(1988, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Email = "michael@nzftc.local",
                            EmployeeCode = "NZFTC1004",
                            FirstName = "Michael",
                            Gender = "Male",
                            JobPositionId = 3,
                            LastName = "Brown",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 8,
                            StartDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1005,
                            Address = "8 Harbour View",
                            Birthday = new DateTime(1999, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Email = "olivia@nzftc.local",
                            EmployeeCode = "NZFTC1005",
                            FirstName = "Olivia",
                            Gender = "Female",
                            JobPositionId = 32,
                            LastName = "Chen",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 2,
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1006,
                            Address = "55 Tech Lane",
                            Birthday = new DateTime(1996, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "daniel@nzftc.local",
                            EmployeeCode = "NZFTC1006",
                            FirstName = "Daniel",
                            Gender = "Male",
                            JobPositionId = 24,
                            LastName = "Lee",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 2,
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1007,
                            Address = "21 Ledger Street",
                            Birthday = new DateTime(1994, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Email = "emma@nzftc.local",
                            EmployeeCode = "NZFTC1007",
                            FirstName = "Emma",
                            Gender = "Female",
                            JobPositionId = 8,
                            LastName = "Johnson",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 2,
                            StartDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1008,
                            Address = "3 Riverbank Road",
                            Birthday = new DateTime(1992, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Email = "liam@nzftc.local",
                            EmployeeCode = "NZFTC1008",
                            FirstName = "Liam",
                            Gender = "Male",
                            JobPositionId = 28,
                            LastName = "Davis",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayFrequency = (byte)0,
                            PayGradeId = 4,
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeEmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmergencyContactId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmergencyContactId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeemergencycontacts", (string)null);

                    b.HasData(
                        new
                        {
                            EmergencyContactId = 1,
                            Email = "none@local",
                            EmployeeId = 1001,
                            FullName = "Admin Contact",
                            Phone = "0000"
                        },
                        new
                        {
                            EmergencyContactId = 2,
                            Email = "jane.doe@example.com",
                            EmployeeId = 1002,
                            FullName = "Jane Doe",
                            Phone = "0211234567"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("EmployeeLeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeLeaveBalanceId"));

                    b.Property<decimal>("AnnualAccrued")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AnnualUsed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CarryOverAnnual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SickAccrued")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SickUsed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EmployeeLeaveBalanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeleavebalances", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeLeaveBalanceId = 1,
                            AnnualAccrued = 10m,
                            AnnualUsed = 2m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1001,
                            SickAccrued = 5m,
                            SickUsed = 1m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 2,
                            AnnualAccrued = 8m,
                            AnnualUsed = 1m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1002,
                            SickAccrued = 4m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 3,
                            AnnualAccrued = 5m,
                            AnnualUsed = 0m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1003,
                            SickAccrued = 2m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 4,
                            AnnualAccrued = 10m,
                            AnnualUsed = 2m,
                            CarryOverAnnual = 1m,
                            EmployeeId = 1004,
                            SickAccrued = 5m,
                            SickUsed = 1m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 5,
                            AnnualAccrued = 6m,
                            AnnualUsed = 0m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1005,
                            SickAccrued = 3m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 6,
                            AnnualAccrued = 7m,
                            AnnualUsed = 1m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1006,
                            SickAccrued = 4m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 7,
                            AnnualAccrued = 9m,
                            AnnualUsed = 2m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1007,
                            SickAccrued = 5m,
                            SickUsed = 1m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 8,
                            AnnualAccrued = 12m,
                            AnnualUsed = 3m,
                            CarryOverAnnual = 2m,
                            EmployeeId = 1008,
                            SickAccrued = 6m,
                            SickUsed = 1m,
                            UpdatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeePayrollSummary", b =>
                {
                    b.Property<int>("EmployeePayrollSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeePayrollSummaryId"));

                    b.Property<decimal>("ACCLevy")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Deductions")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GrossPay")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("KiwiSaverEmployee")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("KiwiSaverEmployer")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("PAYE")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PayRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("PayrollPeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("PayrollRunId")
                        .HasColumnType("int");

                    b.Property<byte>("RateType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("StudentLoan")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("EmployeePayrollSummaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("employeepayrollsummaries", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeePayrollSummaryId = 1,
                            ACCLevy = 15m,
                            Deductions = 260m,
                            EmployeeId = 1001,
                            GeneratedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 2000m,
                            KiwiSaverEmployee = 45m,
                            KiwiSaverEmployer = 45m,
                            NetPay = 1740m,
                            PAYE = 200m,
                            PayRate = 50.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 1,
                            RateType = (byte)0,
                            Status = (byte)2,
                            StudentLoan = 0m,
                            TotalHours = 40m
                        },
                        new
                        {
                            EmployeePayrollSummaryId = 2,
                            ACCLevy = 12m,
                            Deductions = 202m,
                            EmployeeId = 1002,
                            GeneratedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 1330m,
                            KiwiSaverEmployee = 40m,
                            KiwiSaverEmployer = 40m,
                            NetPay = 1128m,
                            PAYE = 150m,
                            PayRate = 35.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 1,
                            RateType = (byte)0,
                            Status = (byte)2,
                            StudentLoan = 0m,
                            TotalHours = 38m
                        },
                        new
                        {
                            EmployeePayrollSummaryId = 3,
                            ACCLevy = 14m,
                            Deductions = 260m,
                            EmployeeId = 1003,
                            GeneratedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 1890m,
                            KiwiSaverEmployee = 56m,
                            KiwiSaverEmployer = 56m,
                            NetPay = 1630m,
                            PAYE = 190m,
                            PayRate = 45.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 1,
                            RateType = (byte)0,
                            Status = (byte)2,
                            StudentLoan = 0m,
                            TotalHours = 42m
                        },
                        new
                        {
                            EmployeePayrollSummaryId = 4,
                            ACCLevy = 15m,
                            Deductions = 260m,
                            EmployeeId = 1001,
                            GeneratedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 2000m,
                            KiwiSaverEmployee = 45m,
                            KiwiSaverEmployer = 45m,
                            NetPay = 1740m,
                            PAYE = 200m,
                            PayRate = 50.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 2,
                            RateType = (byte)0,
                            Status = (byte)0,
                            StudentLoan = 0m,
                            TotalHours = 40m
                        },
                        new
                        {
                            EmployeePayrollSummaryId = 5,
                            ACCLevy = 17m,
                            Deductions = 344m,
                            EmployeeId = 1004,
                            GeneratedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 2220m,
                            KiwiSaverEmployee = 67m,
                            KiwiSaverEmployer = 67m,
                            NetPay = 1876m,
                            PAYE = 260m,
                            PayRate = 60.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 2,
                            RateType = (byte)0,
                            Status = (byte)0,
                            StudentLoan = 0m,
                            TotalHours = 37m
                        },
                        new
                        {
                            EmployeePayrollSummaryId = 6,
                            ACCLevy = 7m,
                            Deductions = 122m,
                            EmployeeId = 1005,
                            GeneratedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrossPay = 840m,
                            KiwiSaverEmployee = 25m,
                            KiwiSaverEmployer = 25m,
                            NetPay = 718m,
                            PAYE = 90m,
                            PayRate = 28.00m,
                            PayrollPeriodId = 1,
                            PayrollRunId = 3,
                            RateType = (byte)0,
                            Status = (byte)0,
                            StudentLoan = 0m,
                            TotalHours = 30m
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Grievance", b =>
                {
                    b.Property<int>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GrievanceId"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GrievanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Grievances");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HolidayType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsPaidHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("HolidayId");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("holidays", (string)null);

                    b.HasData(
                        new
                        {
                            HolidayId = 1,
                            HolidayDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "New Year's Day"
                        },
                        new
                        {
                            HolidayId = 2,
                            HolidayDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Day After New Year's Day"
                        },
                        new
                        {
                            HolidayId = 3,
                            HolidayDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Waitangi Day"
                        },
                        new
                        {
                            HolidayId = 4,
                            HolidayDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Good Friday"
                        },
                        new
                        {
                            HolidayId = 5,
                            HolidayDate = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Easter Monday"
                        },
                        new
                        {
                            HolidayId = 6,
                            HolidayDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "ANZAC Day"
                        },
                        new
                        {
                            HolidayId = 7,
                            HolidayDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "King's Birthday"
                        },
                        new
                        {
                            HolidayId = 8,
                            HolidayDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Matariki"
                        },
                        new
                        {
                            HolidayId = 9,
                            HolidayDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Labour Day"
                        },
                        new
                        {
                            HolidayId = 10,
                            HolidayDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Christmas Day"
                        },
                        new
                        {
                            HolidayId = 11,
                            HolidayDate = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Boxing Day"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.JobPosition", b =>
                {
                    b.Property<int>("JobPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JobPositionId"));

                    b.Property<string>("AccessRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PayGradeId")
                        .HasColumnType("int");

                    b.HasKey("JobPositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PayGradeId");

                    b.ToTable("jobpositions", (string)null);

                    b.HasData(
                        new
                        {
                            JobPositionId = 1,
                            AccessRole = "Admin",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Chief Financial Officer (CFO)",
                            PayGradeId = 10
                        },
                        new
                        {
                            JobPositionId = 2,
                            AccessRole = "Admin",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Finance Manager",
                            PayGradeId = 9
                        },
                        new
                        {
                            JobPositionId = 3,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Senior Accountant",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 4,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Accountant",
                            PayGradeId = 7
                        },
                        new
                        {
                            JobPositionId = 5,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Accounts Payable Officer",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 6,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Accounts Receivable Officer",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 7,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Payroll Officer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 8,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Finance Administrator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 9,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Billing Specialist",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 10,
                            AccessRole = "Employee",
                            Department = "Finance",
                            IsActive = true,
                            Name = "Accounts Assistant",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 11,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "HR Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 12,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "Senior HR Advisor",
                            PayGradeId = 7
                        },
                        new
                        {
                            JobPositionId = 13,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "HR Advisor",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 14,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "HR Coordinator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 15,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "HR Administrator",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 16,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "Recruitment Specialist",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 17,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "Talent Acquisition Coordinator",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 18,
                            AccessRole = "Admin",
                            Department = "HR",
                            IsActive = true,
                            Name = "Training & Development Officer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 19,
                            AccessRole = "Admin",
                            Department = "IT",
                            IsActive = true,
                            Name = "IT Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 20,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Systems Administrator",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 21,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Network Administrator",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 22,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Software Developer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 23,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Application Support Analyst",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 24,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "IT Support Technician",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 25,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Helpdesk Support",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 26,
                            AccessRole = "Employee",
                            Department = "IT",
                            IsActive = true,
                            Name = "Database Administrator (DBA)",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 27,
                            AccessRole = "Admin",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Operations Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 28,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Team Leader – Operations",
                            PayGradeId = 4
                        },
                        new
                        {
                            JobPositionId = 29,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Supervisor – Operations",
                            PayGradeId = 5
                        },
                        new
                        {
                            JobPositionId = 30,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Senior Officer – Operations",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 31,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Office Administrator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 32,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Customer Service Representative",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 33,
                            AccessRole = "Employee",
                            Department = "Operations",
                            IsActive = true,
                            Name = "Data Entry Operator",
                            PayGradeId = 1
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.LeavePolicy", b =>
                {
                    b.Property<int>("LeavePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeavePolicyId"));

                    b.Property<bool>("AllowNegativeAnnual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowUnpaidSick")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("AnnualAccrualRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AnnualCarryOverLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AnnualDefault")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CustomLeaveTypesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SickAccrualRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SickDefault")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LeavePolicyId");

                    b.ToTable("leavepolicies", (string)null);

                    b.HasData(
                        new
                        {
                            LeavePolicyId = 1,
                            AllowNegativeAnnual = false,
                            AllowUnpaidSick = true,
                            AnnualAccrualRate = 1.67m,
                            AnnualCarryOverLimit = 5m,
                            AnnualDefault = 20m,
                            CustomLeaveTypesJson = "[]",
                            SickAccrualRate = 0m,
                            SickDefault = 10m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("leaverequests", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveRequestId = 1,
                            EmployeeId = 1002,
                            EndDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Family event",
                            RequestedAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            LeaveRequestId = 2,
                            ApprovedAt = new DateTime(2025, 11, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovedByEmployeeId = 1001,
                            EmployeeId = 1003,
                            EndDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Sick",
                            Reason = "Flu",
                            RequestedAt = new DateTime(2025, 11, 17, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            LeaveRequestId = 3,
                            ApprovedAt = new DateTime(2025, 11, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovedByEmployeeId = 1001,
                            EmployeeId = 1004,
                            EndDate = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Overlaps with year-end close",
                            RequestedAt = new DateTime(2025, 11, 22, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected"
                        },
                        new
                        {
                            LeaveRequestId = 4,
                            EmployeeId = 1005,
                            EndDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Sick",
                            Reason = "Migraine",
                            RequestedAt = new DateTime(2025, 11, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            LeaveRequestId = 5,
                            ApprovedAt = new DateTime(2025, 11, 19, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovedByEmployeeId = 1001,
                            EmployeeId = 1006,
                            EndDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Short break",
                            RequestedAt = new DateTime(2025, 11, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayGrade", b =>
                {
                    b.Property<int>("PayGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayGradeId"));

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("RateType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("PayGradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("paygrades", (string)null);

                    b.HasData(
                        new
                        {
                            PayGradeId = 1,
                            BaseRate = 23.50m,
                            Description = "Minimum Pay",
                            IsActive = true,
                            Name = "PG-minimum",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 2,
                            BaseRate = 28.00m,
                            Description = "Regular Staff",
                            IsActive = true,
                            Name = "PG-REG",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 3,
                            BaseRate = 32.00m,
                            Description = "Senior Staff",
                            IsActive = true,
                            Name = "PG-SSTAFF",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 4,
                            BaseRate = 38.00m,
                            Description = "Team Leader",
                            IsActive = true,
                            Name = "PG-TL",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 5,
                            BaseRate = 45.00m,
                            Description = "Supervisor",
                            IsActive = true,
                            Name = "PG-SUP",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 6,
                            BaseRate = 50.00m,
                            Description = "Specialist",
                            IsActive = true,
                            Name = "PG-SPEC",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 7,
                            BaseRate = 65000m,
                            Description = "Salary - Junior/Assistant Manager",
                            IsActive = true,
                            Name = "PG-SAL-JM",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 8,
                            BaseRate = 80000m,
                            Description = "Salary - Department Manager",
                            IsActive = true,
                            Name = "PG-SAL-MAN",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 9,
                            BaseRate = 95000m,
                            Description = "Salary - Senior Manager",
                            IsActive = true,
                            Name = "PG-SAL-SRMAN",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 10,
                            BaseRate = 100000m,
                            Description = "Salary - General Manager",
                            IsActive = true,
                            Name = "PG-SAL-GM",
                            RateType = (byte)1
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollPeriod", b =>
                {
                    b.Property<int>("PayrollPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollPeriodId"));

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("PayrollPeriodId");

                    b.HasIndex("PeriodCode")
                        .IsUnique();

                    b.ToTable("payrollperiods", (string)null);

                    b.HasData(
                        new
                        {
                            PayrollPeriodId = 1,
                            Closed = false,
                            PeriodCode = "2025-M11",
                            PeriodEnd = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0m
                        },
                        new
                        {
                            PayrollPeriodId = 2,
                            Closed = false,
                            PeriodCode = "2025-M12",
                            PeriodEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0m
                        },
                        new
                        {
                            PayrollPeriodId = 3,
                            Closed = true,
                            PeriodCode = "2025-FN13",
                            PeriodEnd = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 90000m
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollRun", b =>
                {
                    b.Property<int>("PayrollRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollRunId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PayFrequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PayrollRunId");

                    b.ToTable("payrollruns", (string)null);

                    b.HasData(
                        new
                        {
                            PayrollRunId = 1,
                            CreatedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidAt = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayFrequency = 0,
                            PeriodEnd = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcessedAt = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            PayrollRunId = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayFrequency = 0,
                            PeriodEnd = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            PayrollRunId = 3,
                            CreatedAt = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayFrequency = 0,
                            PeriodEnd = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollSettings", b =>
                {
                    b.Property<int>("PayrollSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollSettingsId"));

                    b.Property<decimal>("ACCLevyPercent")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.Property<bool>("EnableStudentLoan")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("KiwiSaverEmployeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("KiwiSaverEmployerPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OvertimeMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RegularHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PayrollSettingsId");

                    b.ToTable("payrollsettings", (string)null);

                    b.HasData(
                        new
                        {
                            PayrollSettingsId = 1,
                            ACCLevyPercent = 1.53m,
                            EnableStudentLoan = true,
                            KiwiSaverEmployeePercent = 3.0m,
                            KiwiSaverEmployerPercent = 3.0m,
                            OvertimeMultiplier = 1.5m,
                            RegularHoursPerWeek = 40,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AdminReplyAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("SenderEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("SenderIsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("supportmessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hi, I need help setting up my account.",
                            SenderEmployeeId = 1002,
                            SenderIsAdmin = false,
                            SentAt = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "Admin here — your account is now active!",
                            SenderEmployeeId = 1001,
                            SenderIsAdmin = true,
                            SentAt = new DateTime(2025, 11, 20, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "I get a red error banner when I click submit.",
                            SenderEmployeeId = 1005,
                            SenderIsAdmin = false,
                            SentAt = new DateTime(2025, 11, 21, 9, 32, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 2
                        },
                        new
                        {
                            Id = 4,
                            Body = "Can you send me a screenshot of the error?",
                            SenderEmployeeId = 1006,
                            SenderIsAdmin = true,
                            SentAt = new DateTime(2025, 11, 21, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 2
                        },
                        new
                        {
                            Id = 5,
                            Body = "My timesheet shows 42 hours but payslip only paid 40.",
                            SenderEmployeeId = 1004,
                            SenderIsAdmin = false,
                            SentAt = new DateTime(2025, 11, 18, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 3
                        },
                        new
                        {
                            Id = 6,
                            Body = "We’re checking your timesheet against the payroll run.",
                            SenderEmployeeId = 1001,
                            SenderIsAdmin = true,
                            SentAt = new DateTime(2025, 11, 19, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("supporttickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 1001,
                            CreatedAt = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1002,
                            Message = "This is the initial seeded support ticket.",
                            Priority = 0,
                            Status = 0,
                            Subject = "Welcome to Support"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 1006,
                            CreatedAt = new DateTime(2025, 11, 21, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1005,
                            Message = "I get an error when submitting my timesheet for this week.",
                            Priority = 2,
                            Status = 0,
                            Subject = "Cannot submit timesheet",
                            UpdatedAt = new DateTime(2025, 11, 21, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AssignedToId = 1001,
                            CreatedAt = new DateTime(2025, 11, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1004,
                            Message = "My overtime for last week is missing.",
                            Priority = 2,
                            Status = 1,
                            Subject = "Payslip amount seems incorrect",
                            UpdatedAt = new DateTime(2025, 11, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.TimesheetEntry", b =>
                {
                    b.Property<int>("TimesheetEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimesheetEntryId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("BreakEndTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("BreakStartTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("time(6)");

                    b.Property<int?>("PayrollRunId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("TimesheetEntryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("timesheetentries", (string)null);

                    b.HasData(
                        new
                        {
                            TimesheetEntryId = 1,
                            AdminNote = "Approved – standard day.",
                            ApprovedAt = new DateTime(2025, 11, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            BreakEndTime = new TimeSpan(0, 12, 30, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 7, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1001,
                            FinishTime = new TimeSpan(0, 17, 0, 0, 0),
                            PayrollRunId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 7, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 7.5m,
                            WorkDate = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 2,
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1002,
                            FinishTime = new TimeSpan(0, 17, 0, 0, 0),
                            PayrollRunId = 1,
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            Status = 1,
                            SubmittedAt = new DateTime(2025, 11, 11, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.0m,
                            WorkDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 3,
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 12, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1002,
                            FinishTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = 0,
                            TotalHours = 8.5m,
                            WorkDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 4,
                            AdminNote = "Approved – includes 0.5h overtime.",
                            ApprovedAt = new DateTime(2025, 11, 11, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            BreakEndTime = new TimeSpan(0, 13, 30, 0, 0),
                            BreakStartTime = new TimeSpan(0, 13, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 10, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1003,
                            FinishTime = new TimeSpan(0, 18, 0, 0, 0),
                            PayrollRunId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 10, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.5m,
                            WorkDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 5,
                            AdminNote = "Incorrect break time; please resubmit.",
                            ApprovedAt = new DateTime(2025, 11, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            BreakEndTime = new TimeSpan(0, 14, 30, 0, 0),
                            BreakStartTime = new TimeSpan(0, 14, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 9, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1004,
                            FinishTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 11, 9, 19, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.5m,
                            WorkDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 6,
                            ApprovedAt = new DateTime(2025, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1005,
                            FinishTime = new TimeSpan(0, 17, 0, 0, 0),
                            PayrollRunId = 2,
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 14, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.0m,
                            WorkDate = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 7,
                            BreakEndTime = new TimeSpan(0, 13, 30, 0, 0),
                            BreakStartTime = new TimeSpan(0, 13, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 15, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1006,
                            FinishTime = new TimeSpan(0, 18, 0, 0, 0),
                            PayrollRunId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = 1,
                            SubmittedAt = new DateTime(2025, 11, 15, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.5m,
                            WorkDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 8,
                            BreakEndTime = new TimeSpan(0, 13, 0, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 16, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1007,
                            FinishTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = 0,
                            TotalHours = 8.0m,
                            WorkDate = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimesheetEntryId = 9,
                            AdminNote = "Approved – training coverage.",
                            ApprovedAt = new DateTime(2025, 11, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            BreakEndTime = new TimeSpan(0, 12, 30, 0, 0),
                            BreakStartTime = new TimeSpan(0, 12, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 11, 21, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1008,
                            FinishTime = new TimeSpan(0, 16, 30, 0, 0),
                            PayrollRunId = 3,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 21, 16, 40, 0, 0, DateTimeKind.Unspecified),
                            TotalHours = 8.0m,
                            WorkDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NZFTC_EMS.Data.Entities.PayGrade", "PayGrade")
                        .WithMany()
                        .HasForeignKey("PayGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JobPosition");

                    b.Navigation("PayGrade");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeEmergencyContact", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeePayrollSummary", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("PayrollSummaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZFTC_EMS.Data.Entities.PayrollPeriod", "PayrollPeriod")
                        .WithMany("PayrollSummaries")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NZFTC_EMS.Data.Entities.PayrollRun", "PayrollRun")
                        .WithMany("Payslips")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Grievance", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.JobPosition", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.PayGrade", "PayGrade")
                        .WithMany("JobPositions")
                        .HasForeignKey("PayGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PayGrade");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.LeaveRequest", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportMessage", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZFTC_EMS.Data.Entities.PayrollRun", "PayrollRun")
                        .WithMany()
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollSummaries");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayGrade", b =>
                {
                    b.Navigation("JobPositions");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollPeriod", b =>
                {
                    b.Navigation("PayrollSummaries");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollRun", b =>
                {
                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
