// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZFTC_EMS.Data;

#nullable disable

namespace NZFTC_EMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119172906_FullSync")]
    partial class FullSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "NZFTC EMS officially launched!",
                            End = new DateTime(2025, 11, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 3,
                            OwnerUsername = "System",
                            Start = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "System Go-Live"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<int?>("PayGradeId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("JobPositionId");

                    b.HasIndex("PayGradeId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1001,
                            Address = "N/A",
                            Department = "HR",
                            Email = "admin@nzftc.local",
                            EmployeeCode = "TEMP001",
                            FirstName = "Temp",
                            Gender = "N/A",
                            JobPositionId = 11,
                            LastName = "Admin",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayGradeId = 8,
                            StartDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 1002,
                            Address = "N/A",
                            Department = "Operations",
                            Email = "emp@nzftc.local",
                            EmployeeCode = "TEMP002",
                            FirstName = "Temp",
                            Gender = "N/A",
                            JobPositionId = 31,
                            LastName = "Employee",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            PayGradeId = 2,
                            StartDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeEmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmergencyContactId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmergencyContactId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeemergencycontacts", (string)null);

                    b.HasData(
                        new
                        {
                            EmergencyContactId = 1,
                            Email = "none@local",
                            EmployeeId = 1001,
                            FullName = "Temp Admin Contact",
                            Phone = "0000",
                            Relationship = "N/A"
                        },
                        new
                        {
                            EmergencyContactId = 2,
                            Email = "none@local",
                            EmployeeId = 1002,
                            FullName = "Temp Employee Contact",
                            Phone = "0000",
                            Relationship = "N/A"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("EmployeeLeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeLeaveBalanceId"));

                    b.Property<decimal>("AnnualAccrued")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AnnualUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CarryOverAnnual")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SickAccrued")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SickUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EmployeeLeaveBalanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employeeleavebalances", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeLeaveBalanceId = 1,
                            AnnualAccrued = 0m,
                            AnnualUsed = 0m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1001,
                            SickAccrued = 0m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeLeaveBalanceId = 2,
                            AnnualAccrued = 0m,
                            AnnualUsed = 0m,
                            CarryOverAnnual = 0m,
                            EmployeeId = 1002,
                            SickAccrued = 0m,
                            SickUsed = 0m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeePayrollSummary", b =>
                {
                    b.Property<int>("EmployeePayrollSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeePayrollSummaryId"));

                    b.Property<decimal>("Deductions")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossPay")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("NetPay")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasComputedColumnSql("(`GrossPay` - `Deductions`)", true);

                    b.Property<decimal>("PayRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("EmployeePayrollSummaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("employeepayrollsummaries", (string)null);
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Grievance", b =>
                {
                    b.Property<int>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GrievanceId"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GrievanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("grievances", (string)null);
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsPaidHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("HolidayId");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("holidays", (string)null);

                    b.HasData(
                        new
                        {
                            HolidayId = 1,
                            HolidayDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "New Year's Day"
                        },
                        new
                        {
                            HolidayId = 2,
                            HolidayDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Waitangi Day"
                        },
                        new
                        {
                            HolidayId = 3,
                            HolidayDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Good Friday"
                        },
                        new
                        {
                            HolidayId = 4,
                            HolidayDate = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "Easter Monday"
                        },
                        new
                        {
                            HolidayId = 5,
                            HolidayDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayType = "Public",
                            IsPaidHoliday = true,
                            Name = "ANZAC Day"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.JobPosition", b =>
                {
                    b.Property<int>("JobPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JobPositionId"));

                    b.Property<string>("AccessRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PayGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("PayGradeId1")
                        .HasColumnType("int");

                    b.HasKey("JobPositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PayGradeId");

                    b.HasIndex("PayGradeId1");

                    b.ToTable("jobpositions", (string)null);

                    b.HasData(
                        new
                        {
                            JobPositionId = 1,
                            AccessRole = "Admin",
                            Department = "Finance",
                            Description = "Top-level finance leadership",
                            IsActive = true,
                            Name = "Chief Financial Officer (CFO)",
                            PayGradeId = 10
                        },
                        new
                        {
                            JobPositionId = 2,
                            AccessRole = "Admin",
                            Department = "Finance",
                            Description = "Leads the finance team and reporting",
                            IsActive = true,
                            Name = "Finance Manager",
                            PayGradeId = 9
                        },
                        new
                        {
                            JobPositionId = 3,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Handles complex accounting and reporting",
                            IsActive = true,
                            Name = "Senior Accountant",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 4,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "General accounting duties",
                            IsActive = true,
                            Name = "Accountant",
                            PayGradeId = 7
                        },
                        new
                        {
                            JobPositionId = 5,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Manages supplier invoices and payments",
                            IsActive = true,
                            Name = "Accounts Payable Officer",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 6,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Manages customer invoicing and collections",
                            IsActive = true,
                            Name = "Accounts Receivable Officer",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 7,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Processes staff payroll",
                            IsActive = true,
                            Name = "Payroll Officer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 8,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Provides general admin support to finance",
                            IsActive = true,
                            Name = "Finance Administrator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 9,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Prepares and manages billing",
                            IsActive = true,
                            Name = "Billing Specialist",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 10,
                            AccessRole = "Employee",
                            Department = "Finance",
                            Description = "Entry-level support in finance",
                            IsActive = true,
                            Name = "Accounts Assistant",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 11,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Leads HR operations and strategy",
                            IsActive = true,
                            Name = "HR Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 12,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Senior advisory role in HR",
                            IsActive = true,
                            Name = "Senior HR Advisor",
                            PayGradeId = 7
                        },
                        new
                        {
                            JobPositionId = 13,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Generalist HR support",
                            IsActive = true,
                            Name = "HR Advisor",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 14,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Coordinates HR processes and documentation",
                            IsActive = true,
                            Name = "HR Coordinator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 15,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Admin support across HR functions",
                            IsActive = true,
                            Name = "HR Administrator",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 16,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Manages recruitment and selection",
                            IsActive = true,
                            Name = "Recruitment Specialist",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 17,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Supports talent acquisition activities",
                            IsActive = true,
                            Name = "Talent Acquisition Coordinator",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 18,
                            AccessRole = "Admin",
                            Department = "HR",
                            Description = "Coordinates training and staff development",
                            IsActive = true,
                            Name = "Training & Development Officer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 19,
                            AccessRole = "Admin",
                            Department = "IT",
                            Description = "Leads IT operations and projects",
                            IsActive = true,
                            Name = "IT Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 20,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Maintains servers and systems",
                            IsActive = true,
                            Name = "Systems Administrator",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 21,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Manages network infrastructure",
                            IsActive = true,
                            Name = "Network Administrator",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 22,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Develops and maintains software applications",
                            IsActive = true,
                            Name = "Software Developer",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 23,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Supports business applications",
                            IsActive = true,
                            Name = "Application Support Analyst",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 24,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "First-line IT support",
                            IsActive = true,
                            Name = "IT Support Technician",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 25,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Handles basic IT helpdesk requests",
                            IsActive = true,
                            Name = "Helpdesk Support",
                            PayGradeId = 1
                        },
                        new
                        {
                            JobPositionId = 26,
                            AccessRole = "Employee",
                            Department = "IT",
                            Description = "Manages databases and performance",
                            IsActive = true,
                            Name = "Database Administrator (DBA)",
                            PayGradeId = 6
                        },
                        new
                        {
                            JobPositionId = 27,
                            AccessRole = "Admin",
                            Department = "Operations",
                            Description = "Oversees day-to-day operations",
                            IsActive = true,
                            Name = "Operations Manager",
                            PayGradeId = 8
                        },
                        new
                        {
                            JobPositionId = 28,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "Leads an operations team",
                            IsActive = true,
                            Name = "Team Leader – Operations",
                            PayGradeId = 4
                        },
                        new
                        {
                            JobPositionId = 29,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "Supervises operational staff",
                            IsActive = true,
                            Name = "Supervisor – Operations",
                            PayGradeId = 5
                        },
                        new
                        {
                            JobPositionId = 30,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "Senior operations officer role",
                            IsActive = true,
                            Name = "Senior Officer – Operations",
                            PayGradeId = 3
                        },
                        new
                        {
                            JobPositionId = 31,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "General office administration",
                            IsActive = true,
                            Name = "Office Administrator",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 32,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "Frontline customer service",
                            IsActive = true,
                            Name = "Customer Service Representative",
                            PayGradeId = 2
                        },
                        new
                        {
                            JobPositionId = 33,
                            AccessRole = "Employee",
                            Department = "Operations",
                            Description = "Data entry and basic admin tasks",
                            IsActive = true,
                            Name = "Data Entry Operator",
                            PayGradeId = 1
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedByEmployeeEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("ApprovedByEmployeeEmployeeId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("leaverequests", (string)null);
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayGrade", b =>
                {
                    b.Property<int>("PayGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayGradeId"));

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("RateType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("PayGradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("paygrades", (string)null);

                    b.HasData(
                        new
                        {
                            PayGradeId = 1,
                            BaseRate = 23.50m,
                            Description = "Minimum Pay",
                            IsActive = true,
                            Name = "PG-minimum",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 2,
                            BaseRate = 28.00m,
                            Description = "Regular Staff",
                            IsActive = true,
                            Name = "PG-REG",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 3,
                            BaseRate = 32.00m,
                            Description = "Senior Staff",
                            IsActive = true,
                            Name = "PG-SSTAFF",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 4,
                            BaseRate = 38.00m,
                            Description = "Team Leader",
                            IsActive = true,
                            Name = "PG-TL",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 5,
                            BaseRate = 45.00m,
                            Description = "Supervisor",
                            IsActive = true,
                            Name = "PG-SUP",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 6,
                            BaseRate = 50.00m,
                            Description = "Specialist",
                            IsActive = true,
                            Name = "PG-SPEC",
                            RateType = (byte)0
                        },
                        new
                        {
                            PayGradeId = 7,
                            BaseRate = 65000.00m,
                            Description = "Salary - Junior/Assistant Manager",
                            IsActive = true,
                            Name = "PG-SAL-JM",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 8,
                            BaseRate = 80000.00m,
                            Description = "Salary - Department Manager",
                            IsActive = true,
                            Name = "PG-SAL-MAN",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 9,
                            BaseRate = 95000.00m,
                            Description = "Salary - Senior Manager",
                            IsActive = true,
                            Name = "PG-SAL-SRMAN",
                            RateType = (byte)1
                        },
                        new
                        {
                            PayGradeId = 10,
                            BaseRate = 100000.00m,
                            Description = "Salary - General Manager",
                            IsActive = true,
                            Name = "PG-SAL-GM",
                            RateType = (byte)1
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollPeriod", b =>
                {
                    b.Property<int>("PayrollPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollPeriodId"));

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("PayrollPeriodId");

                    b.HasIndex("PeriodCode")
                        .IsUnique();

                    b.ToTable("payrollperiods", (string)null);

                    b.HasData(
                        new
                        {
                            PayrollPeriodId = 1,
                            Closed = false,
                            PeriodCode = "2025-11-M1",
                            PeriodEnd = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStart = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0.00m
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AdminReplyAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("SenderEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("SenderIsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("supportmessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hi, I need help setting up my account.",
                            SenderEmployeeId = 1002,
                            SenderIsAdmin = false,
                            SentAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "Admin here — your account is now active!",
                            SenderEmployeeId = 1001,
                            SenderIsAdmin = false,
                            SentAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketId = 1
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("supporttickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 1001,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1002,
                            Message = "This is a sample seeded ticket.",
                            Priority = 0,
                            Status = 0,
                            Subject = "Welcome to Support"
                        });
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NZFTC_EMS.Data.Entities.PayGrade", "PayGrade")
                        .WithMany()
                        .HasForeignKey("PayGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JobPosition");

                    b.Navigation("PayGrade");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeEmergencyContact", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.EmployeePayrollSummary", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("PayrollSummaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NZFTC_EMS.Data.Entities.PayrollPeriod", "PayrollPeriod")
                        .WithMany("Summaries")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Grievance", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("Grievances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.JobPosition", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.PayGrade", null)
                        .WithMany()
                        .HasForeignKey("PayGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NZFTC_EMS.Data.Entities.PayGrade", "PayGrade")
                        .WithMany()
                        .HasForeignKey("PayGradeId1");

                    b.Navigation("PayGrade");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.LeaveRequest", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeEmployeeId");

                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportMessage", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.HasOne("NZFTC_EMS.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.Employee", b =>
                {
                    b.Navigation("EmergencyContacts");

                    b.Navigation("Grievances");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollSummaries");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.PayrollPeriod", b =>
                {
                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("NZFTC_EMS.Data.Entities.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
